const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS'
const GET_POKEMON_NAME = 'GET_POKEMON_NAME'
const GET_TYPES = 'GET_TYPES'
const GET_POKEMON_ID = 'GET_POKEMON_ID'
const FILTER_TYPE = 'FILTER_TYPE'
const ORDER_BY = 'ORDER_BY'
const FILTER_ORIGIN = 'FILTER_ORIGIN'
const RESET_DETAIL = 'RESET_DETAIL'

export {
    GET_ALL_POKEMONS,
    GET_POKEMON_NAME,
    GET_TYPES,
    GET_POKEMON_ID,
    FILTER_TYPE,
    ORDER_BY,
    FILTER_ORIGIN,
    RESET_DETAIL
}